---
title: "All Decades Summary Table"
author: "Shawn Behrend"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This code reads each of the Years per Decade summary tables created in the previous piece of code to create an overall summary table.
```{r}
# read summary table files
sum_1880_1889_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1880_1889/1880_1889_summary_table.csv")
sum_1890_1899_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1890_1899/1890_1899_summary_table.csv")
sum_1900_1909_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1900_1909/1900_1909_summary_table.csv")
sum_1910_1919_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1910_1919/1910_1919_summary_table.csv")
sum_1920_1929_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1920_1929/1920_1929_summary_table.csv")
sum_1930_1939_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1930_1939/1930_1939_summary_table.csv")
sum_1940_1949_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1940_1949/1940_1949_summary_table.csv")
sum_1950_1959_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1950_1959/1950_1959_summary_table.csv")
sum_1960_1969_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1960_1969/1960_1969_summary_table.csv")
sum_1970_1979_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1970_1979/1970_1979_summary_table.csv")
sum_1980_1989_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1980_1989/1980_1989_summary_table.csv")
sum_1990_1999_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/1990_1999/1990_1999_summary_table.csv")
sum_2000_2009_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/2000_2009/2000_2009_summary_table.csv")
sum_2010_2020_df<-read.csv("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/2010_2020/2010_2020_summary_table.csv")

#write_summary table vectors for each decade
tot_1880_1889_summary<-c("1880-1889",sum_1880_1889_df[10,3],sum(sum_1880_1889_df[6]),
                         sum(sum_1880_1889_df[7]),sum(sum_1880_1889_df[6])/sum(sum_1880_1889_df[7]),sum(sum_1880_1889_df[9]),sum(sum_1880_1889_df[10]), sum(sum_1880_1889_df[9])/sum(sum_1880_1889_df[10]),sum(sum_1880_1889_df[12]),sum(sum_1880_1889_df[13]),sum(sum_1880_1889_df[12])/sum(sum_1880_1889_df[13]))
tot_1890_1899_summary<-c("1890-1899",sum_1890_1899_df[10,3],sum(sum_1890_1899_df[6]),sum(sum_1890_1899_df[7]), sum(sum_1890_1899_df[6])/sum(sum_1890_1899_df[7]),sum(sum_1890_1899_df[9]),sum(sum_1890_1899_df[10]), sum(sum_1890_1899_df[9])/sum(sum_1890_1899_df[10]),sum(sum_1890_1899_df[12]),sum(sum_1890_1899_df[13]),sum(sum_1890_1899_df[12])/sum(sum_1890_1899_df[13]))
tot_1900_1909_summary<-c("1900-1909",sum_1900_1909_df[10,3],sum(sum_1900_1909_df[6]),sum(sum_1900_1909_df[7]), sum(sum_1900_1909_df[6])/sum(sum_1900_1909_df[7]),sum(sum_1900_1909_df[9]),sum(sum_1900_1909_df[10]), sum(sum_1900_1909_df[9])/sum(sum_1900_1909_df[10]),sum(sum_1900_1909_df[12]),sum(sum_1900_1909_df[13]),sum(sum_1900_1909_df[12])/sum(sum_1900_1909_df[13]))
tot_1910_1919_summary<-c("1910-1919",sum_1910_1919_df[10,3],sum(sum_1910_1919_df[6]),sum(sum_1910_1919_df[7]), sum(sum_1910_1919_df[6])/sum(sum_1910_1919_df[7]),sum(sum_1910_1919_df[9]),sum(sum_1910_1919_df[10]), sum(sum_1910_1919_df[9])/sum(sum_1910_1919_df[10]),sum(sum_1910_1919_df[12]),sum(sum_1910_1919_df[13]),sum(sum_1910_1919_df[12])/sum(sum_1910_1919_df[13]))
tot_1920_1929_summary<-c("1920-1929",sum_1920_1929_df[10,3],sum(sum_1920_1929_df[6]),sum(sum_1920_1929_df[7]),sum(sum_1920_1929_df[6])/sum(sum_1920_1929_df[7]),sum(sum_1920_1929_df[9]),sum(sum_1920_1929_df[10]), sum(sum_1920_1929_df[9])/sum(sum_1920_1929_df[10]),sum(sum_1920_1929_df[12]),sum(sum_1920_1929_df[13]),sum(sum_1920_1929_df[12])/sum(sum_1920_1929_df[13]))
tot_1930_1939_summary<-c("1930-1939",sum_1930_1939_df[10,3],sum(sum_1930_1939_df[6]),sum(sum_1930_1939_df[7]), sum(sum_1930_1939_df[6])/sum(sum_1930_1939_df[7]),sum(sum_1930_1939_df[9]),sum(sum_1930_1939_df[10]), sum(sum_1930_1939_df[9])/sum(sum_1930_1939_df[10]),sum(sum_1930_1939_df[12]),sum(sum_1930_1939_df[13]),sum(sum_1930_1939_df[12])/sum(sum_1930_1939_df[13]))
tot_1940_1949_summary<-c("1940-1949",sum_1940_1949_df[10,3],sum(sum_1940_1949_df[6]),sum(sum_1940_1949_df[7]), sum(sum_1940_1949_df[6])/sum(sum_1940_1949_df[7]),sum(sum_1940_1949_df[9]),sum(sum_1940_1949_df[10]),sum(sum_1940_1949_df[9])/sum(sum_1940_1949_df[10]),sum(sum_1940_1949_df[12]),sum(sum_1940_1949_df[13]),sum(sum_1940_1949_df[12])/sum(sum_1940_1949_df[13]))
tot_1950_1959_summary<-c("1950-1959",sum_1950_1959_df[10,3],sum(sum_1950_1959_df[6]),sum(sum_1950_1959_df[7]),sum(sum_1950_1959_df[6])/sum(sum_1950_1959_df[7]),sum(sum_1950_1959_df[9]),sum(sum_1950_1959_df[10]),sum(sum_1950_1959_df[9])/sum(sum_1950_1959_df[10]),sum(sum_1950_1959_df[12]),sum(sum_1950_1959_df[13]),sum(sum_1950_1959_df[12])/sum(sum_1950_1959_df[13]))
tot_1960_1969_summary<-c("1960-1969",sum_1960_1969_df[10,3],sum(sum_1960_1969_df[6]),sum(sum_1960_1969_df[7]),sum(sum_1960_1969_df[6])/sum(sum_1960_1969_df[7]),sum(sum_1960_1969_df[9]),sum(sum_1960_1969_df[10]),sum(sum_1960_1969_df[9])/sum(sum_1960_1969_df[10]),sum(sum_1960_1969_df[12]),sum(sum_1960_1969_df[13]),sum(sum_1960_1969_df[12])/sum(sum_1960_1969_df[13]))
tot_1970_1979_summary<-c("1970-1979",sum_1970_1979_df[10,3],sum(sum_1970_1979_df[6]),sum(sum_1970_1979_df[7]),sum(sum_1970_1979_df[6])/sum(sum_1970_1979_df[7]),sum(sum_1970_1979_df[9]),sum(sum_1970_1979_df[10]),sum(sum_1970_1979_df[9])/sum(sum_1970_1979_df[10]),sum(sum_1970_1979_df[12]),sum(sum_1970_1979_df[13]),sum(sum_1970_1979_df[12])/sum(sum_1970_1979_df[13]))
tot_1980_1989_summary<-c("1980-1989",sum_1980_1989_df[10,3],sum(sum_1980_1989_df[6]),sum(sum_1980_1989_df[7]),sum(sum_1980_1989_df[6])/sum(sum_1980_1989_df[7]),sum(sum_1980_1989_df[9]),sum(sum_1980_1989_df[10]),sum(sum_1980_1989_df[9])/sum(sum_1980_1989_df[10]),sum(sum_1980_1989_df[12]),sum(sum_1980_1989_df[13]),sum(sum_1980_1989_df[12])/sum(sum_1980_1989_df[13]))
tot_1990_1999_summary<-c("1990-1999",sum_1990_1999_df[10,3],sum(sum_1990_1999_df[6]),sum(sum_1990_1999_df[7]),sum(sum_1990_1999_df[6])/sum(sum_1990_1999_df[7]),sum(sum_1990_1999_df[9]),sum(sum_1990_1999_df[10]),sum(sum_1990_1999_df[9])/sum(sum_1990_1999_df[10]),sum(sum_1990_1999_df[12]),sum(sum_1990_1999_df[13]),sum(sum_1990_1999_df[12])/sum(sum_1990_1999_df[13]))
tot_2000_2009_summary<-c("2000-2009",sum_2000_2009_df[10,3],sum(sum_2000_2009_df[6]),sum(sum_2000_2009_df[7]),sum(sum_2000_2009_df[6])/sum(sum_2000_2009_df[7]),sum(sum_2000_2009_df[9]),sum(sum_2000_2009_df[10]),sum(sum_2000_2009_df[9])/sum(sum_2000_2009_df[10]),sum(sum_2000_2009_df[12]),sum(sum_2000_2009_df[13]),sum(sum_2000_2009_df[12])/sum(sum_2000_2009_df[13]))
tot_2010_2020_summary<-c("2010-2020",sum_2010_2020_df[10,3],sum(sum_2010_2020_df[6]),sum(sum_2010_2020_df[7]),sum(sum_2010_2020_df[6])/sum(sum_2010_2020_df[7]),sum(sum_2010_2020_df[9]),sum(sum_2010_2020_df[10]),sum(sum_2010_2020_df[9])/sum(sum_2010_2020_df[10]),sum(sum_2010_2020_df[12]),sum(sum_2010_2020_df[13]),sum(sum_2010_2020_df[12])/sum(sum_2010_2020_df[13]))
#--- Assemble table for all decades
decades_table<-t(data.frame(tot_1880_1889_summary,tot_1890_1899_summary,tot_1900_1909_summary,tot_1910_1919_summary,tot_1920_1929_summary,                  tot_1930_1939_summary,tot_1940_1949_summary,tot_1950_1959_summary,tot_1960_1969_summary,tot_1970_1979_summary,                        tot_1980_1989_summary,tot_1990_1999_summary,tot_2000_2009_summary,tot_2010_2020_summary))
colnames(decades_table)<-c("Years","# of GN Names","F occurrances of GN names","Total F occurrances","Ratio of F GN Occur to Total F Occur",
                                 "M occurrances of GN names","Total M occurrances","Ratio of M GN Occur to Total M Occur",
                                 "Total GN Occurrances","Total Occurrances","Ratio of GN Occurrances to Total Occurrances")
rownames(decades_table)<-NULL
#save to data file
write.csv(x=decades_table,file=("C:/Users/shawn/OneDrive/Shawn/CSU_global/MIS581/project_r_code/name_files/all_decades_summary_table.csv"))
```
An excerpt of the first few rows of the All Decades Summary Table that were saved to CSV above is shown here.
```{r}
head(decades_table,10)
```